repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff
        args: [--fix]
        files: '^scripts/'
      - id: ruff-format
        files: '^scripts/'

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        files: '^scripts/'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: '^(scripts|web/src|tests)/'
      - id: end-of-file-fixer
        files: '^(scripts|web/src|tests)/'
