import json

import data_utils
import pytest
from data_utils import (
    collect_subjects,
    collect_terms_by_year,
    diff_term_names,
    get_academic_year,
    partition_subject_by_year,
    render_subjects_module,
    render_terms_module,
)


@pytest.mark.parametrize(
    "term_name, expected",
    [
        ("2025-26 Term 2", "2025-26"),
        ("2026-27 Term 1", "2026-27"),  # the other year live during the transition
        ("2025-26 Acad Year (Medicine)", "2025-26"),  # real term with an unusual suffix
    ],
)
def test_get_academic_year(term_name, expected):
    assert get_academic_year(term_name) == expected


def _course(code, term_names):
    return {"course_code": code, "terms": [{"term_name": tn} for tn in term_names]}


def _write_subject_manifest_file(data_root, year, code, title, metadata_subject=None):
    year_dir = data_root / year
    year_dir.mkdir(exist_ok=True)
    data = {
        "metadata": {"subject": metadata_subject or code, "subject_title": title},
        "courses": [],
    }
    (year_dir / f"{code}.json").write_text(json.dumps(data))


def test_collect_subjects_groups_codes_by_year_and_prefers_newest_title(tmp_path):
    _write_subject_manifest_file(tmp_path, "2025-26", "BBBB", "Old B")
    _write_subject_manifest_file(tmp_path, "2025-26", "AAAA", "Subject A")
    _write_subject_manifest_file(tmp_path, "2026-27", "BBBB", "New B")

    subjects_by_year, subject_titles = collect_subjects(tmp_path)

    assert subjects_by_year == {
        "2025-26": ["AAAA", "BBBB"],
        "2026-27": ["BBBB"],
    }
    assert subject_titles == {"AAAA": "Subject A", "BBBB": "New B"}


def test_collect_subjects_rejects_filename_metadata_mismatch(tmp_path):
    _write_subject_manifest_file(tmp_path, "2025-26", "AAAA", "Subject B", metadata_subject="BBBB")

    with pytest.raises(ValueError, match="AAAA.json.*BBBB.*AAAA"):
        collect_subjects(tmp_path)


def test_render_subjects_module_is_deterministic():
    content = render_subjects_module(
        {"2026-27": ["BBBB"], "2025-26": ["AAAA"]},
        {"BBBB": "Dean's Courses", "AAAA": "Subject A"},
    )

    assert (
        content
        == """/**
 * CUHK subject data, auto-generated by scripts/generate_subjects.py.
 * - SUBJECTS_BY_YEAR: subject codes offered in each academic year.
 * - SUBJECT_TITLES: subject code to full title, unioned across years.
 */
export const SUBJECTS_BY_YEAR: Record<string, readonly string[]> = {
  '2025-26': ['AAAA'],
  '2026-27': ['BBBB'],
} as const

export const SUBJECT_TITLES: Record<string, string> = {
  AAAA: 'Subject A',
  BBBB: "Dean's Courses",
} as const
"""
    )


def test_diff_subject_manifest_reports_changes_by_year():
    old = render_subjects_module(
        {
            "2025-26": ["AAAA", "BBBB"],
            "2026-27": ["BBBB", "DDDD"],
            "2027-28": ["FFFF"],
        },
        {
            "AAAA": "Subject A",
            "BBBB": "Subject B",
            "DDDD": "Subject D",
            "FFFF": "Subject F",
        },
    )
    new = render_subjects_module(
        {
            "2025-26": ["BBBB", "CCCC"],
            "2026-27": ["BBBB", "EEEE"],
            "2027-28": ["FFFF"],
        },
        {
            "BBBB": "Subject B",
            "CCCC": "Subject C",
            "EEEE": "Subject E",
            "FFFF": "Subject F",
        },
    )

    changes = data_utils.diff_subject_manifest(old, new)

    assert changes is not None
    assert changes.by_year == {
        "2025-26": data_utils.SubjectYearChanges(added={"CCCC"}, removed={"AAAA"}),
        "2026-27": data_utils.SubjectYearChanges(added={"EEEE"}, removed={"DDDD"}),
    }
    assert changes.changed_titles == set()


def test_diff_subject_manifest_reports_changed_existing_titles():
    old = render_subjects_module({"2025-26": ["AAAA"]}, {"AAAA": "Old title"})
    new = render_subjects_module({"2025-26": ["AAAA"]}, {"AAAA": "New title"})

    changes = data_utils.diff_subject_manifest(old, new)

    assert changes is not None
    assert changes.by_year == {}
    assert changes.changed_titles == {"AAAA"}


def test_diff_subject_manifest_reports_no_changes_for_identical_content():
    content = render_subjects_module({"2025-26": ["AAAA"]}, {"AAAA": "Subject A"})

    changes = data_utils.diff_subject_manifest(content, content)

    assert changes == data_utils.SubjectManifestChanges(by_year={}, changed_titles=set())


@pytest.mark.parametrize("malformed_side", ["old", "new"])
def test_diff_subject_manifest_returns_none_for_malformed_content(malformed_side):
    valid = render_subjects_module({"2025-26": ["AAAA"]}, {"AAAA": "Subject A"})
    old = "not a subjects module" if malformed_side == "old" else valid
    new = "not a subjects module" if malformed_side == "new" else valid

    assert data_utils.diff_subject_manifest(old, new) is None


def test_partition_splits_a_multi_year_course_into_each_year():
    # A course offered in both years lands in each file with only that year's terms;
    # a course with no terms goes to the no-terms bucket.
    data = {
        "metadata": {"subject": "TEST", "subject_title": "Test", "total_courses": 3},
        "courses": [
            _course("1000", ["2025-26 Term 1", "2026-27 Term 1"]),
            _course("2000", ["2025-26 Term 2"]),
            _course("9999", []),
        ],
    }

    parts = partition_subject_by_year(data)

    assert set(parts) == {"2025-26", "2026-27", None}
    y25 = {c["course_code"]: c for c in parts["2025-26"]["courses"]}
    y26 = {c["course_code"]: c for c in parts["2026-27"]["courses"]}
    assert set(y25) == {"1000", "2000"}
    assert set(y26) == {"1000"}
    assert [t["term_name"] for t in y25["1000"]["terms"]] == ["2025-26 Term 1"]
    assert [t["term_name"] for t in y26["1000"]["terms"]] == ["2026-27 Term 1"]
    assert [c["course_code"] for c in parts[None]["courses"]] == ["9999"]


def test_partition_recomputes_total_courses_per_slice():
    # Per-slice count (not the original), so metadata-vs-actual validation passes.
    data = {
        "metadata": {"subject": "TEST", "subject_title": "Test", "total_courses": 2},
        "courses": [_course("1000", ["2025-26 Term 1"]), _course("9999", [])],
    }

    parts = partition_subject_by_year(data)

    assert parts["2025-26"]["metadata"]["total_courses"] == 1
    assert parts[None]["metadata"]["total_courses"] == 1
    assert parts["2025-26"]["metadata"]["subject_title"] == "Test"  # metadata carries over


def test_partition_empty_subject_yields_no_slices():
    # Empty subject -> no slices -> scraper writes no file.
    data = {"metadata": {"subject": "EMPT", "total_courses": 0}, "courses": []}
    assert partition_subject_by_year(data) == {}


def _write_subject_file(tmp_path, filename, term_names):
    data = {
        "metadata": {"subject": filename, "total_courses": 1},
        "courses": [_course("1000", term_names)],
    }
    (tmp_path / f"{filename}.json").write_text(json.dumps(data))


def test_collect_terms_sorts_by_teaching_calendar_order(tmp_path):
    # Terms written out of order across two subjects; output should be sorted
    # Term 1..4, Summer Session, Acad Year (Medicine) - not alphabetically or by
    # first-seen order.
    _write_subject_file(tmp_path, "AAAA", ["2025-26 Summer Session", "2025-26 Term 2"])
    _write_subject_file(tmp_path, "BBBB", ["2025-26 Term 1", "2025-26 Acad Year (Medicine)"])

    result = collect_terms_by_year(tmp_path)

    assert result == {
        "2025-26": [
            "2025-26 Term 1",
            "2025-26 Term 2",
            "2025-26 Summer Session",
            "2025-26 Acad Year (Medicine)",
        ]
    }


def test_collect_terms_dedupes_across_subjects(tmp_path):
    _write_subject_file(tmp_path, "AAAA", ["2025-26 Term 1"])
    _write_subject_file(tmp_path, "BBBB", ["2025-26 Term 1"])

    result = collect_terms_by_year(tmp_path)

    assert result == {"2025-26": ["2025-26 Term 1"]}


def test_collect_terms_excludes_terms_with_no_recognizable_year(tmp_path):
    _write_subject_file(tmp_path, "AAAA", ["TBA", "2025-26 Term 1"])

    result = collect_terms_by_year(tmp_path)

    assert result == {"2025-26": ["2025-26 Term 1"]}


def test_collect_terms_raises_on_unrecognized_suffix(tmp_path):
    # A term suffix not in TERM_SUFFIX_ORDER should fail loudly, not silently sort
    # to the end - CUHK introducing a new term type needs a human to notice.
    _write_subject_file(tmp_path, "AAAA", ["2025-26 Winter Session"])

    with pytest.raises(ValueError):
        collect_terms_by_year(tmp_path)


def test_render_terms_module_output():
    module = render_terms_module({"2025-26": ["2025-26 Term 1", "2025-26 Term 2"]})

    assert (
        module
        == """/**
 * Available terms by academic year.
 * Auto-generated by scripts/publish_course_data.py from the scraped course data.
 */
export const TERMS_BY_YEAR: Record<string, readonly string[]> = {
  '2025-26': [
    '2025-26 Term 1',
    '2025-26 Term 2',
  ],
} as const
"""
    )


def test_diff_term_names_reports_added_and_removed():
    old = render_terms_module({"2025-26": ["2025-26 Term 1", "2025-26 Term 2"]})
    new = render_terms_module({"2025-26": ["2025-26 Term 2", "2025-26 Term 3"]})

    added, removed = diff_term_names(old, new)

    assert added == {"2025-26 Term 3"}
    assert removed == {"2025-26 Term 1"}


def test_diff_term_names_reports_nothing_when_unchanged():
    content = render_terms_module({"2025-26": ["2025-26 Term 1"]})

    added, removed = diff_term_names(content, content)

    assert added == set()
    assert removed == set()


def test_diff_term_names_ignores_year_keys_on_new_year():
    # A whole new year appearing must report only its term names, not the bare
    # "2026-27" object key.
    old = render_terms_module({"2025-26": ["2025-26 Term 1"]})
    new = render_terms_module({"2025-26": ["2025-26 Term 1"], "2026-27": ["2026-27 Term 1"]})

    added, removed = diff_term_names(old, new)

    assert added == {"2026-27 Term 1"}
    assert removed == set()
