#!/usr/bin/env python3
"""
Generate web/src/lib/generated/subjects.ts from the scraped course data.

subjects.ts is the single source of truth for subject data:
- SUBJECTS_BY_YEAR: which subjects each academic year offers (year -> codes)
- SUBJECT_TITLES: code -> title, unioned across years (newest year wins on conflict)

Run when the scraped subject set changes, then review the git diff and commit:
    uv run python scripts/generate_subjects.py
"""

import json
from pathlib import Path

from data_utils import year_dirs

PROJECT_ROOT = Path(__file__).parent.parent
DATA_DIR = PROJECT_ROOT / "data"
SUBJECTS_FILE = PROJECT_ROOT / "web" / "src" / "lib" / "generated" / "subjects.ts"


def format_ts_string(value: str) -> str:
    # Prefer double quotes when the value has an apostrophe (and no double quote)
    # to avoid escaping; single-quote otherwise. subjects.ts is Prettier-ignored,
    # so this is just for clean, valid output.
    escaped = value.replace("\\", "\\\\")
    if "'" in escaped and '"' not in escaped:
        return f'"{escaped}"'
    escaped = escaped.replace("'", "\\'")
    return f"'{escaped}'"


def render_subjects_module(
    subjects_by_year: dict[str, list[str]], subject_titles: dict[str, str]
) -> str:
    lines = [
        "/**",
        " * CUHK subject data, auto-generated by scripts/generate_subjects.py.",
        " * - SUBJECTS_BY_YEAR: subject codes offered in each academic year.",
        " * - SUBJECT_TITLES: subject code to full title, unioned across years.",
        " */",
        "export const SUBJECTS_BY_YEAR: Record<string, readonly string[]> = {",
    ]
    # One line per year: this is machine-owned data no one reads, so don't wrap.
    for year in sorted(subjects_by_year):
        codes = ", ".join(f"'{code}'" for code in subjects_by_year[year])
        lines.append(f"  '{year}': [{codes}],")
    lines.append("} as const")
    lines.append("")
    lines.append("export const SUBJECT_TITLES: Record<string, string> = {")
    for subject in sorted(subject_titles):
        lines.append(f"  {subject}: {format_ts_string(subject_titles[subject])},")
    lines.append("} as const")
    return "\n".join(lines) + "\n"


def main():
    subjects_by_year: dict[str, list[str]] = {}
    subject_titles: dict[str, str] = {}

    # Ascending year order so a newer year's title overwrites an older one.
    for year_dir in year_dirs(DATA_DIR):
        codes = []
        for filepath in sorted(year_dir.glob("*.json")):
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)

            subject = data["metadata"]["subject"]
            codes.append(subject)
            subject_titles[subject] = data["metadata"]["subject_title"]

        subjects_by_year[year_dir.name] = sorted(codes)

    SUBJECTS_FILE.write_text(render_subjects_module(subjects_by_year, subject_titles), "utf-8")
    print(f"Wrote {SUBJECTS_FILE.relative_to(PROJECT_ROOT).as_posix()}")


if __name__ == "__main__":
    main()
